### ISSUE TITLE
postMessage问题

### ISSUE THREAD

**Issue by CrelleZ** [dingyong0214/uni.webview.js#1]
postMessage传参数不能触发web-view里的message应该怎么处理呀

**Comment by dingyong0214** [comment]
怎么调用的





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CrelleZ <notifications@github.com&gt;
发送时间: 2019年10月24日 19:31
收件人: dingyong0214/uni.webview.js <uni.webview.js@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[dingyong0214/uni.webview.js] postMessage问题 (#1)




postMessage传参数不能触发web-view里的message应该怎么处理呀

**Comment by CrelleZ** [comment]
this.tui.postMessage({
   data:{
     action: 'postMessage'
  }
})

**Comment by CrelleZ** [comment]
其他的api都能用，就是postMessage没反应

**Comment by dingyong0214** [comment]
退出页面才执行，什么环境没反应，试一下其他环境



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CrelleZ <notifications@github.com&gt;
发送时间: 2019年10月24日 19:51
收件人: dingyong0214/uni.webview.js <uni.webview.js@noreply.github.com&gt;
抄送: echo. <1062884167@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[dingyong0214/uni.webview.js] postMessage问题 (#1)




其他的api都能用，就是postMessage没反应

**Comment by CrelleZ** [comment]
谢谢，我刚刚找到问题了，是顺序有问题，postMessage必须写在其他事件之前才行
